# Generated by Django 2.1.3 on 2018-11-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name_plural': '确认码',
                'verbose_name': '确认码',
            },
        ),
        migrations.CreateModel(
            name='changePasswordCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name_plural': '修改码',
                'verbose_name': '修改码',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=11, null=True)),
                ('qqNumber', models.CharField(max_length=16, null=True)),
                ('weChatNumber', models.CharField(max_length=50, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('isActivated', models.BooleanField(default=False)),
                ('isStu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
        migrations.AddField(
            model_name='changepasswordcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='identity.User'),
        ),
        migrations.AddField(
            model_name='activatecode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='identity.User'),
        ),
    ]
